# Generated by Django 5.0.7 on 2024-08-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_reset_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
