# Generated by Django 5.0.7 on 2024-08-25 17:21

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='contents',
            field=models.FileField(blank=True, null=True, upload_to=registration.models.content_directory_path),
        ),
        migrations.AddField(
            model_name='services',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
