# Generated by Django 5.0.7 on 2024-08-22 17:54

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='one_time_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='image_path',
            field=models.ImageField(blank=True, default='services_images/default.jpg', null=True, upload_to=registration.models.catalog_directory_path),
        ),
    ]
