# Generated by Django 5.0.7 on 2024-08-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_services_contents_services_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='is_visible',
            new_name='is_visible_content',
        ),
    ]
