# Generated by Django 5.0.7 on 2024-08-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_promocode_one_time_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_promo_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='promo_attempts',
            field=models.IntegerField(default=5),
        ),
    ]
