# Generated by Django 5.0.7 on 2024-08-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_category_is_active_services_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
