# Generated by Django 5.0.7 on 2024-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_bannedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedip',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
