# Generated by Django 5.0.7 on 2024-08-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_is_visible_services_is_visible_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
