# Generated by Django 5.0.7 on 2024-08-23 15:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
