# Generated by Django 5.0.7 on 2024-08-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_services_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='contents',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
