# Generated by Django 5.0.7 on 2024-08-23 16:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
        ),
    ]
