# Generated by Django 5.0.7 on 2024-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_services_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='modified_by_task',
            field=models.BooleanField(default=False),
        ),
    ]
