# Generated by Django 5.0.7 on 2024-08-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_services_modified_by_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='modified_by_task',
        ),
    ]
